### ISSUE TITLE
Verify that LVGL still works

### ISSUE THREAD

**Issue by Richard-Stump** [purduesigbots/liblvgl#10]
Test the LVGL template to verify that it works. Try various features, especially things such as buttons to ensure they work properly. Also test LVGL 8 specific features to ensure that it was upgraded properly

**Comment by WillXuCodes** [comment]
Do you mean LLEMU?*

**Comment by Richard-Stump** [comment]
No, I meant LVGL. It was confirmed to be working, so this is now being closed.
